# Generated by Django 4.2.5 on 2023-10-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser',
        ),
    ]
